# Generated by Django 3.0.6 on 2020-06-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionForm', '0002_auto_20200602_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionForm.Marcas'),
            preserve_default=False,
        ),
    ]
