# Generated by Django 3.0.6 on 2020-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionForm', '0004_auto_20200602_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('dpi', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Trabajadore',
        ),
    ]
