# Generated by Django 3.0.6 on 2020-06-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionForm', '0007_auto_20200602_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
